### ISSUE TITLE
Support elm-explorations/tests v 2.0.1

### ISSUE THREAD

**Issue by janjelinek** [Janiczek/architecture-test#3]
Hi Martin,
can you pls check if your lib is working with latest `elm-explorations/test` and bump supported version so we can use both, your package and new test version in our project? 

I don't want to do any "forky" or copy/paste mojo here :) 
Thx a lot!

```
Error: Failed to solve dependencies for tests to run

Caused by:
    0: Combining the project dependencies with the ones of the test runner failed
    1: Because Janiczek/architecture-test 2.1.0 depends on elm-explorations/test 1.0.0 <= v < 2.0.0 and root/ 0.0.0 depends on elm-explorations/test 2.0.1, Janiczek/architecture-test 2.1.0, root/ 0.0.0 are incompatible.
       And because root/ 0.0.0 depends on Janiczek/architecture-test 2.1.0, root/ 0.0.0 is forbidden.
make: *** [test_share] Error 1

```

**Comment by Janiczek** [comment]
Hey @janjelinek! Of course, I will :) I'll try to do that ~today evening. Thanks for the ping!

**Comment by Janiczek** [comment]
@janjelinek I made `architecture-test` v2.1.1 that has bounds `1.0.0 <= v < 3.0.0` - can you try whether that works? There was no actual code change, but I'm not sure Elm will work with that "more than 1 major version" bound correctly. Please let me know! :)

**Comment by Janiczek** [comment]
I've tried the new package out with both 1.2.2 and 2.0.1 and it works! Thanks again for raising
